# docker-compose.yml
version: '3'
services:
  app:
    build: .
    ports:
      - "3000:80"  # Expose the app on port 3000
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
